=== zhangwei5095/jdbc-shards/src/main/resources/META-INF/ddal-config.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--

		Copyright 2014-2015 the original author or authors
		
		Licensed under the Apache License, Version 2.0 (the “License”);
		you may not use this file except in compliance with the License.
		You may obtain a copy of the License at
		
		     http://www.apache.org/licenses/LICENSE-2.0
		
		Unless required by applicable law or agreed to in writing, software
		distributed under the License is distributed on an “AS IS” BASIS,
		WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
		See the License for the specific language governing permissions and
		limitations under the License.

-->
<!ELEMENT ddal-config (settings?,schema,cluster,dataNodes?,tableRules?,ruleAlgorithms?)>

<!ELEMENT settings (property*)>

<!ELEMENT schema (tableGroup*, table*)>
<!ATTLIST schema
name CDATA #REQUIRED
shard CDATA #IMPLIED
validation (true|false) #IMPLIED
>


<!ELEMENT cluster (shard+)>
<!ELEMENT shard (member+)>
<!ATTLIST shard
name CDATA #REQUIRED
>


<!ELEMENT dataNodes (datasource+)>
<!ELEMENT datasource (property*)>
<!ATTLIST datasource
id CDATA #REQUIRED
class CDATA #IMPLIED
jndi-name CDATA #IMPLIED
>

<!ELEMENT tableRules (tableRule+)>
<!ELEMENT tableRule (#PCDATA)>
<!ATTLIST tableRule
resource CDATA #REQUIRED
>

<!ELEMENT ruleAlgorithms (ruleAlgorithm*)>
<!ELEMENT ruleAlgorithm (property*)>
<!ATTLIST ruleAlgorithm
name CDATA #REQUIRED
class CDATA #REQUIRED
>

<!ELEMENT table (#PCDATA)>
<!ATTLIST table
name CDATA #REQUIRED
router CDATA #IMPLIED
shard CDATA #IMPLIED
validation (true|false) #IMPLIED
scanLevel (unlimited|filter|anyIndex|uniqueIndex|shardingKey) #IMPLIED
>

<!ELEMENT tableGroup (table+)>
<!ATTLIST tableGroup
shard CDATA #IMPLIED
router CDATA #IMPLIED
validation (true|false) #IMPLIED
scanLevel (unlimited|filter|anyIndex|uniqueIndex|shardingKey) #IMPLIED
>

<!ELEMENT property (#PCDATA)>
<!ATTLIST property
name CDATA #REQUIRED
value CDATA #REQUIRED
>


<!ELEMENT member (#PCDATA)>
<!ATTLIST member
ref CDATA #REQUIRED
wWeight CDATA #IMPLIED
rWeight CDATA #IMPLIED
>

=== zhangwei5095/jdbc-shards/src/test/resources/test/sql/ddal-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ddal-config PUBLIC "-//wplatform.com//DTD ddal-config//EN" "http://wplatform.com/dtd/ddal-config.dtd">
<ddal-config>


	<schema name="PUBLIC" shard="shard1" validation="false">

		<tableGroup router="partition_group">
			<table name="partition_parent"/>
			<table name="partition_child"/>
		</tableGroup>

		<table name="replication_parent" shard="shard0,shard1,shard2,shard3"/>
		<table name="replication_child" shard="shard0,shard1,shard2,shard3"/>

		<table name="parent"/>
		<table name="child"/>
		<table name="test"/>
		<table name="t1"/>
	</schema>

	<cluster>
		<shard name="shard0">
			<member ref="db1m"/>
		</shard>
		<shard name="shard1">
			<member ref="db2m"/>
		</shard>
		<shard name="shard2">
			<member ref="db3m"/>
		</shard>
		<shard name="shard3">
			<member ref="db4m"/>
		</shard>
	</cluster>


	<dataNodes>
		<datasource id="db1m" class="org.apache.commons.dbcp.BasicDataSource">
			<property name="driverClassName" value="com.mysql.jdbc.Driver" />
			<property name="url" value="jdbc:mysql://10.199.249.251:3306/ddal_db1" />
			<property name="username" value="root" />
			<property name="password" value="admin" />
		</datasource>
		<datasource id="db2m" class="org.apache.commons.dbcp.BasicDataSource">
			<property name="driverClassName" value="com.mysql.jdbc.Driver" />
			<property name="url" value="jdbc:mysql://10.199.249.251:3306/ddal_db2" />
			<property name="username" value="root" />
			<property name="password" value="admin" />
		</datasource>
		<datasource id="db3m" class="org.apache.commons.dbcp.BasicDataSource">
			<property name="driverClassName" value="com.mysql.jdbc.Driver" />
			<property name="url" value="jdbc:mysql://10.199.249.251:3306/ddal_db3" />
			<property name="username" value="root" />
			<property name="password" value="admin" />
		</datasource>
		<datasource id="db4m" class="org.apache.commons.dbcp.BasicDataSource">
			<property name="driverClassName" value="com.mysql.jdbc.Driver" />
			<property name="url" value="jdbc:mysql://10.199.249.251:3306/ddal_db4" />
			<property name="username" value="root" />
			<property name="password" value="admin" />
		</datasource>
	</dataNodes>
	
	
	<tableRules>
		<tableRule resource="test/sql/ddal-rule.xml"/>
	</tableRules>

</ddal-config>

=== zhangwei5095/jdbc-shards/src/test/resources/config/ddal-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ddal-config PUBLIC "-//wplatform.com//DTD ddal-config//EN" "http://wplatform.com/dtd/ddal-config.dtd">
<ddal-config>

	<schema name="myApp" shard="shard0">
	
		<tableGroup router="customer_group" validation="false">
			<table name="customers"/>
			<table name="address"/>
		</tableGroup>	

		<tableGroup router="order_group" validation="false">
			<table name="orders"/>
			<table name="order_items"/>
			<table name="order_status"/>
		</tableGroup>
		
		<table name="product" validation="false"/>
		<table name="product_category" validation="false"/>

	</schema>

	<cluster>
		<shard name="shard0">
			<member ref="db1m"/>
		</shard>
		<shard name="shard1">
			<member ref="db2m"/>
		</shard>
		<shard name="shard2">
			<member ref="db3m"/>
		</shard>
		<shard name="shard3">
			<member ref="db4m"/>
		</shard>
	</cluster>


	<dataNodes>
		<datasource id="db1m" class="org.apache.commons.dbcp.BasicDataSource">
			<property name="driverClassName" value="com.mysql.jdbc.Driver" />
			<property name="url" value="jdbc:mysql://10.199.249.251:3306/ddal_db1" />
			<property name="username" value="root" />
			<property name="password" value="admin" />
			<property name="maxWait" value="1"/>  
		</datasource>
		<datasource id="db2m" class="org.apache.commons.dbcp.BasicDataSource">
			<property name="driverClassName" value="com.mysql.jdbc.Driver" />
			<property name="url" value="jdbc:mysql://10.199.249.251:3306/ddal_db2" />
			<property name="username" value="root" />
			<property name="password" value="admin" />
			<property name="maxWait" value="1"/>  
		</datasource>
		<datasource id="db3m" class="org.apache.commons.dbcp.BasicDataSource">
			<property name="driverClassName" value="com.mysql.jdbc.Driver" />
			<property name="url" value="jdbc:mysql://10.199.249.251:3306/ddal_db3" />
			<property name="username" value="root" />
			<property name="password" value="admin" />
			<property name="maxWait" value="1"/>  
		</datasource>
		<datasource id="db4m" class="org.apache.commons.dbcp.BasicDataSource">
			<property name="driverClassName" value="com.mysql.jdbc.Driver" />
			<property name="url" value="jdbc:mysql://10.199.249.251:3306/ddal_db4" />
			<property name="username" value="root" />
			<property name="password" value="admin" />
			<property name="maxWait" value="1"/>  
		</datasource>
		<!--
		<datasource id="db1s" class="org.apache.commons.dbcp.BasicDataSource">
			<property name="driverClassName" value="com.mysql.jdbc.Driver" />
			<property name="url" value="jdbc:mysql://10.199.249.251:3306/ddal_db1" />
			<property name="username" value="root" />
			<property name="password" value="admin" />
			<property name="maxWait" value="1"/>  
		</datasource>
		<datasource id="db2s" class="org.apache.commons.dbcp.BasicDataSource">
			<property name="driverClassName" value="com.mysql.jdbc.Driver" />
			<property name="url" value="jdbc:mysql://10.19.90.77:3306/ddal_db2" />
			<property name="username" value="root" />
			<property name="password" value="admin" />
			<property name="maxWait" value="1"/>  
		</datasource>
		<datasource id="db3s" class="org.apache.commons.dbcp.BasicDataSource">
			<property name="driverClassName" value="com.mysql.jdbc.Driver" />
			<property name="url" value="jdbc:mysql://10.19.90.77:3306/ddal_db3" />
			<property name="username" value="root" />
			<property name="password" value="admin" />
			<property name="maxWait" value="1"/>  
		</datasource>
		<datasource id="db4s" class="org.apache.commons.dbcp.BasicDataSource">
			<property name="driverClassName" value="com.mysql.jdbc.Driver" />
			<property name="url" value="jdbc:mysql://10.19.90.77:3306/ddal_db4" />
			<property name="username" value="root" />
			<property name="password" value="admin" />
			<property name="maxWait" value="1"/>  
		</datasource>
		-->
	</dataNodes>
	
	
	<tableRules>
		<tableRule resource="/config/ddal-rule.xml"/>
	</tableRules>

</ddal-config>
